// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.15.1
// source: azurefile_mount.proto

package pb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type MountAzureFileRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Source           string   `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Target           string   `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	Fstype           string   `protobuf:"bytes,3,opt,name=fstype,proto3" json:"fstype,omitempty"`
	MountOptions     []string `protobuf:"bytes,4,rep,name=mountOptions,proto3" json:"mountOptions,omitempty"`
	SensitiveOptions []string `protobuf:"bytes,5,rep,name=sensitiveOptions,proto3" json:"sensitiveOptions,omitempty"`
}

func (x *MountAzureFileRequest) Reset() {
	*x = MountAzureFileRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_azurefile_mount_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MountAzureFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MountAzureFileRequest) ProtoMessage() {}

func (x *MountAzureFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_azurefile_mount_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MountAzureFileRequest.ProtoReflect.Descriptor instead.
func (*MountAzureFileRequest) Descriptor() ([]byte, []int) {
	return file_azurefile_mount_proto_rawDescGZIP(), []int{0}
}

func (x *MountAzureFileRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *MountAzureFileRequest) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *MountAzureFileRequest) GetFstype() string {
	if x != nil {
		return x.Fstype
	}
	return ""
}

func (x *MountAzureFileRequest) GetMountOptions() []string {
	if x != nil {
		return x.MountOptions
	}
	return nil
}

func (x *MountAzureFileRequest) GetSensitiveOptions() []string {
	if x != nil {
		return x.SensitiveOptions
	}
	return nil
}

type MountAzureFileResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *MountAzureFileResponse) Reset() {
	*x = MountAzureFileResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_azurefile_mount_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MountAzureFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MountAzureFileResponse) ProtoMessage() {}

func (x *MountAzureFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_azurefile_mount_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MountAzureFileResponse.ProtoReflect.Descriptor instead.
func (*MountAzureFileResponse) Descriptor() ([]byte, []int) {
	return file_azurefile_mount_proto_rawDescGZIP(), []int{1}
}

type UnmountAzureFileRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Target string `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
}

func (x *UnmountAzureFileRequest) Reset() {
	*x = UnmountAzureFileRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_azurefile_mount_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnmountAzureFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnmountAzureFileRequest) ProtoMessage() {}

func (x *UnmountAzureFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_azurefile_mount_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnmountAzureFileRequest.ProtoReflect.Descriptor instead.
func (*UnmountAzureFileRequest) Descriptor() ([]byte, []int) {
	return file_azurefile_mount_proto_rawDescGZIP(), []int{2}
}

func (x *UnmountAzureFileRequest) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

type UnmountAzureFileResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UnmountAzureFileResponse) Reset() {
	*x = UnmountAzureFileResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_azurefile_mount_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnmountAzureFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnmountAzureFileResponse) ProtoMessage() {}

func (x *UnmountAzureFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_azurefile_mount_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnmountAzureFileResponse.ProtoReflect.Descriptor instead.
func (*UnmountAzureFileResponse) Descriptor() ([]byte, []int) {
	return file_azurefile_mount_proto_rawDescGZIP(), []int{3}
}

var File_azurefile_mount_proto protoreflect.FileDescriptor

var file_azurefile_mount_proto_rawDesc = []byte{
	0x0a, 0x15, 0x61, 0x7a, 0x75, 0x72, 0x65, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x6d, 0x6f, 0x75, 0x6e,
	0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xaf, 0x01, 0x0a, 0x15, 0x4d, 0x6f, 0x75, 0x6e,
	0x74, 0x41, 0x7a, 0x75, 0x72, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x61, 0x72,
	0x67, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x61, 0x72, 0x67, 0x65,
	0x74, 0x12, 0x16, 0x0a, 0x06, 0x66, 0x73, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x66, 0x73, 0x74, 0x79, 0x70, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x6d, 0x6f, 0x75,
	0x6e, 0x74, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x0c, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x2a, 0x0a,
	0x10, 0x73, 0x65, 0x6e, 0x73, 0x69, 0x74, 0x69, 0x76, 0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x09, 0x52, 0x10, 0x73, 0x65, 0x6e, 0x73, 0x69, 0x74, 0x69,
	0x76, 0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x18, 0x0a, 0x16, 0x4d, 0x6f, 0x75,
	0x6e, 0x74, 0x41, 0x7a, 0x75, 0x72, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x31, 0x0a, 0x17, 0x55, 0x6e, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x41, 0x7a,
	0x75, 0x72, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16,
	0x0a, 0x06, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x22, 0x1a, 0x0a, 0x18, 0x55, 0x6e, 0x6d, 0x6f, 0x75, 0x6e,
	0x74, 0x41, 0x7a, 0x75, 0x72, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x32, 0x9e, 0x01, 0x0a, 0x0c, 0x4d, 0x6f, 0x75, 0x6e, 0x74, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x43, 0x0a, 0x0e, 0x4d, 0x6f, 0x75, 0x6e, 0x74, 0x41, 0x7a, 0x75, 0x72,
	0x65, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x16, 0x2e, 0x4d, 0x6f, 0x75, 0x6e, 0x74, 0x41, 0x7a, 0x75,
	0x72, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e,
	0x4d, 0x6f, 0x75, 0x6e, 0x74, 0x41, 0x7a, 0x75, 0x72, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x49, 0x0a, 0x10, 0x55, 0x6e, 0x6d, 0x6f,
	0x75, 0x6e, 0x74, 0x41, 0x7a, 0x75, 0x72, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x18, 0x2e, 0x55,
	0x6e, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x41, 0x7a, 0x75, 0x72, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x55, 0x6e, 0x6d, 0x6f, 0x75, 0x6e, 0x74,
	0x41, 0x7a, 0x75, 0x72, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_azurefile_mount_proto_rawDescOnce sync.Once
	file_azurefile_mount_proto_rawDescData = file_azurefile_mount_proto_rawDesc
)

func file_azurefile_mount_proto_rawDescGZIP() []byte {
	file_azurefile_mount_proto_rawDescOnce.Do(func() {
		file_azurefile_mount_proto_rawDescData = protoimpl.X.CompressGZIP(file_azurefile_mount_proto_rawDescData)
	})
	return file_azurefile_mount_proto_rawDescData
}

var file_azurefile_mount_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_azurefile_mount_proto_goTypes = []interface{}{
	(*MountAzureFileRequest)(nil),    // 0: MountAzureFileRequest
	(*MountAzureFileResponse)(nil),   // 1: MountAzureFileResponse
	(*UnmountAzureFileRequest)(nil),  // 2: UnmountAzureFileRequest
	(*UnmountAzureFileResponse)(nil), // 3: UnmountAzureFileResponse
}
var file_azurefile_mount_proto_depIdxs = []int32{
	0, // 0: MountService.MountAzureFile:input_type -> MountAzureFileRequest
	2, // 1: MountService.UnmountAzureFile:input_type -> UnmountAzureFileRequest
	1, // 2: MountService.MountAzureFile:output_type -> MountAzureFileResponse
	3, // 3: MountService.UnmountAzureFile:output_type -> UnmountAzureFileResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_azurefile_mount_proto_init() }
func file_azurefile_mount_proto_init() {
	if File_azurefile_mount_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_azurefile_mount_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MountAzureFileRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_azurefile_mount_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MountAzureFileResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_azurefile_mount_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UnmountAzureFileRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_azurefile_mount_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UnmountAzureFileResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_azurefile_mount_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_azurefile_mount_proto_goTypes,
		DependencyIndexes: file_azurefile_mount_proto_depIdxs,
		MessageInfos:      file_azurefile_mount_proto_msgTypes,
	}.Build()
	File_azurefile_mount_proto = out.File
	file_azurefile_mount_proto_rawDesc = nil
	file_azurefile_mount_proto_goTypes = nil
	file_azurefile_mount_proto_depIdxs = nil
}
